// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTv6C6B-evjKzkYYr3o3ZFT_XO7iPeeRY',
    appId: '1:658104774918:web:cfcf95f9677f4139c2ae87',
    messagingSenderId: '658104774918',
    projectId: 'myrecipebox-fa056',
    authDomain: 'myrecipebox-fa056.firebaseapp.com',
    storageBucket: 'myrecipebox-fa056.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSxiAhXdJqdlpGv5jk3RkEVavptPe5DW0',
    appId: '1:658104774918:android:52687af089132655c2ae87',
    messagingSenderId: '658104774918',
    projectId: 'myrecipebox-fa056',
    storageBucket: 'myrecipebox-fa056.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhUqthqXjJbIlwjoyro0A1xioMtKXB7WU',
    appId: '1:658104774918:ios:c74159352a200810c2ae87',
    messagingSenderId: '658104774918',
    projectId: 'myrecipebox-fa056',
    storageBucket: 'myrecipebox-fa056.firebasestorage.app',
    iosBundleId: 'com.example.myRecipeBox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhUqthqXjJbIlwjoyro0A1xioMtKXB7WU',
    appId: '1:658104774918:ios:c74159352a200810c2ae87',
    messagingSenderId: '658104774918',
    projectId: 'myrecipebox-fa056',
    storageBucket: 'myrecipebox-fa056.firebasestorage.app',
    iosBundleId: 'com.example.myRecipeBox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTv6C6B-evjKzkYYr3o3ZFT_XO7iPeeRY',
    appId: '1:658104774918:web:c903761cd123ceedc2ae87',
    messagingSenderId: '658104774918',
    projectId: 'myrecipebox-fa056',
    authDomain: 'myrecipebox-fa056.firebaseapp.com',
    storageBucket: 'myrecipebox-fa056.firebasestorage.app',
  );
}
